# Generated by Django 5.2.3 on 2026-07-02 23:24

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptGEE',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fuente', models.CharField(max_length=10)),
                ('archivo_csv', models.CharField(max_length=200)),
                ('columnas_detectadas', models.JSONField(default=list)),
                ('columnas_extra', models.JSONField(default=list)),
                ('registros_importados', models.IntegerField(default=0)),
                ('registros_rechazados', models.IntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scripts_gee',
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('zona_nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fuente', models.CharField(max_length=10)),
                ('temperatura_c', models.FloatField(blank=True, null=True)),
                ('temperatura_min_c', models.FloatField(blank=True, null=True)),
                ('temperatura_max_c', models.FloatField(blank=True, null=True)),
                ('precipitacion_mm', models.FloatField(blank=True, null=True)),
                ('dewpoint_c', models.FloatField(blank=True, null=True)),
                ('viento_u', models.FloatField(blank=True, null=True)),
                ('viento_v', models.FloatField(blank=True, null=True)),
                ('humedad_suelo', models.FloatField(blank=True, null=True)),
                ('cobertura_nieve', models.FloatField(blank=True, null=True)),
                ('radiacion_solar', models.FloatField(blank=True, null=True)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('evi', models.FloatField(blank=True, null=True)),
                ('quality_modis', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField(default=dict)),
                ('validado', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zonas.zona')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediciones.scriptgee')),
            ],
            options={
                'db_table': 'mediciones',
            },
        ),
    ]
