# Generated by Django 5.2.3 on 2026-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='codigo_ine',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
